In [18]:
import numpy as np
import tensorflow as tf

print(tf.__version__)
inp = [[1,0,1],[1,1,1],[1,0,1]]
inp = np.array(inp)
print(inp)

model  = tf.keras.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=100,activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(units=9,activation=tf.keras.activations.relu)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(np.array([inp]), np.array([1]))

model.summary()


2.1.0
[[1 0 1]
 [1 1 1]
 [1 0 1]]
Train on 1 samples
1/1 [==============================] - 1s 770ms/sample - loss: 1.7171 - accuracy: 0.0000e+00
Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_13 (Flatten)         multiple                  0         
_________________________________________________________________
dense_25 (Dense)             multiple                  1000      
_________________________________________________________________
dense_26 (Dense)             multiple                  909       
Total params: 1,909
Trainable params: 1,909
Non-trainable params: 0
_________________________________________________________________
